# Generated by Django 3.2.7 on 2024-01-08 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('number_of_rooms', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('room_number', models.PositiveIntegerField(verbose_name=4)),
                ('room_price', models.IntegerField(verbose_name=10)),
                ('room_description', models.TextField(verbose_name=600)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.apartment')),
            ],
        ),
    ]
