# Generated by Django 3.2.7 on 2024-01-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_updatemodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='room number', max_length=20),
        ),
    ]
